### ISSUE TITLE
compiling TMB on Mac OS X 10.11

### ISSUE THREAD

**Issue by JennaVergeynst** [baktoft/yaps_sciRep#1]
Hi,

Trying to run the example code runMe.R on Mac OS X 10.11, RStudio version 3.4.3.
I installed TMB, but when compiling yaps (or when testing TMB with `runExample(all=TRUE)`, I get following error:
`clang: error: unsupported option '-fopenmp'`
`make: *** [linreg_parallel.o] Error 1`
`Error in compile(paste0(name, ".cpp"), ...) : Compilation failed`
`Timing stopped at: 0.014 0.017 0.036`

Any idea what the problem would be?

Thanks,
Jenna

**Comment by baktoft** [comment]
Hi Jenna,

This must be an issue with TMB. I have never seen it when running on Windows (7 & 10) or Ubuntu, so can't really help you. Suggest you contact the TMB-developer @kaskr about this.

Cheers,
\Henrik

**Comment by kaskr** [comment]
@JennaVergeynst 
It seems your compiler doesn't support parallel models. That's not necessarily a problem as most models don't benefit from parallelization anyway...
If you can just run

```
runExample("simple")
```

everything should be fine.

**Comment by baktoft** [comment]
@JennaVergeynst 
YAPS is actually running in parallel, but this is easy to change. 
In the yaps.cpp file, uncomment line 37 (Type nll;) and comment out line 38, so it reads like this:
   Type nll;
   // parallel_accumulator<Type> nll(this);

Cheers,
\hb

**Comment by kaskr** [comment]
...and remember to initialize `nll` to zero.

**Comment by JennaVergeynst** [comment]
Ah, indeed got a warning :-)
Yes, that works now, thanks to both of you!

**Comment by JennaVergeynst** [comment]
@kaskr 
I come back on this, because actually it would be great for performance if I would be able to run in parallel... With 'compiler', do you mean the TMB compiler? Or is it due to the R itself? Is there a way to get a compiler that does support parallel models?

**Comment by baktoft** [comment]
Hi Jenna,
From my experience, YAPS doesn't benefit much (if any at all) from running in parallel. To speed up things, I suggest to run several instances of the model (each estimating track of different fish) using functions in package parallel.
Cheers, \hb

**Comment by JennaVergeynst** [comment]
Hi Henrik,
The reason why I came up with this, is because YAPS runs much slower on my version (where I turned off parallel) than on Thomas’ version (who could keep parallel) for the same tracks, i.e. more than 10 times slower.
What do you mean with “using functions in package parallel”? I’m not so good acquainted with R...
Jenna


——

Jenna Vergeynst
PhD Researcher
BIOMATH - Model-based analysis and optimisation of bioprocesses

BIOMATH just launched a new website, check it out!<http://biomath.ugent.be/>

Department of Data Analysis and Mathematical Modelling
Faculty of Bioscience Engineering
Ghent University
Coupure Links 653, 9000 Gent, Belgium
tel +32 9 264 59 35 fax +32 9 264 62 20

On 20 Aug 2018, at 18:32, Henrik Baktoft <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jenna,
From my experience, YAPS doesn't benefit much (if any at all) from running in parallel. To speed up things, I suggest to run several instances of the model (each estimating track of different fish) using functions in package parallel.
Cheers, \hb

**Comment by baktoft** [comment]
Personal message sent.
